### ISSUE TITLE
Do not use ObjectReference before ensuring it is valid.

### ISSUE THREAD

**Issue by wks** [mmtk/mmtk-core#1042]
This main affects `memory_manager::is_in_mmtk_spaces`.  This method is mainly intended to distinguish between an object reference of an MMTk object and a pointer to some memory allocated by `malloc` or other memory allocators.  Its argument `object: ObjectReference` may or may not be a valid reference to an MMTk object.  If we are not sure, we should use `Address` as its argument type.  Solving this problem will also make it easier to remove `ObjectReference::NULL` from MMTk core.

A related function is `is_mmtk_object`.  It accepts an `Address` as parameter, but requires the user to do an unsafe `ObjectReference::from_raw_address` after it.  However, after `is_mmtk_object` returns `true`, it is actually safe to turn the address to an objref.  So there should be a function that takes `Address` as parameter, and returns `Option<ObjectReference>`.  It should return `Some(objref)` if `is_mmtk_object` returns true for that address, and `None` otherwise.

**Comment by qinsoon** [comment]
An `ObjectReference` may refer to a valid object, but the object may not exist in MMTk spaces. I think `memory_manager::is_in_mmtk_spaces` implies the `ObjectReference` is valid, but the caller/binding is not sure if the object is in the MMTk heap.

**Comment by wks** [comment]
@qinsoon If an object is valid, but not in any MMTk spaces, does it imply that it is in a VM space?  We also have `ActivePlan::vm_trace_object`.  Maybe that implies an `ObjectReference` can point anywhere, not necessarily into MMTk spaces.

**Comment by wks** [comment]
OK.  I think it is clear now.  If `is_in_mmtk_space` takes an `ObjectReference` as argument, the caller (i.e. the binding) is responsible for its validity.  References to VM-allocated memory (such as malloc-ed memory, or anything that works with `ActivePlan::vm_trace_object`) are also considered valid.
