### ISSUE TITLE
Sanity GC is broken

### ISSUE THREAD

**Issue by angussidney** [mmtk/mmtk-core#1078]
In the latest version of MMTk (mmtk-core commit 42754a5f23, mmtk-openjdk commit 54f6688fe4), the Sanity GC is broken.

```
MTK_PLAN=Immix ~/honours/openjdk-builds/20240130-mmtk-slowdebug-42754a5
f2-upstream/bin/java -XX:+UseThirdPartyHeap -Xms512M -Xmx512M -jar /usr/share/benchmarks/dacap
o/dacapo-23.11-chopin.jar lusearch                                                            
[2024-01-30T00:31:21Z INFO  mmtk::memory_manager] Initialized MMTk with Immix (FixedHeapSize(5
36870912))                                                                                    
Using scaled threading model. 24 processors detected, 24 threads used to drive the workload, i
n a possible range of [1,2048]                                                                
Version: lucene 9.7.0 (use -p to print nominal benchmark stats)                               
[2024-01-30T00:31:25Z INFO  mmtk::mmtk] User triggering collection                            
[2024-01-30T00:31:25Z INFO  mmtk::util::sanity::sanity_checker] Sanity GC prepare             
thread 'thread 'thread 'thread 'thread '<unnamed>thread 'thread 'thread '<unnamed><unnamed><un
named><unnamed>' panicked at 'thread '<unnamed><unnamed><unnamed><unnamed>thread '' panicked a
t 'thread '' panicked at 'thread '' panicked at 'thread 'internal error: entered unreachable c
ode: `MutatorConfig::prepare_func` must not be called for the current plan.' panicked at 'thre
ad 'internal error: entered unreachable code: `MutatorConfig::prepare_func` must not be called
 for the current plan.'  

[...]

fatal runtime error: failed to initiate panic, error 
5

Aborted (core dumped)
```

This is occurring because the [sanity GC issues a `PrepareMutator` work packet for each mutator](https://github.com/mmtk/mmtk-core/blob/master/src/util/sanity/sanity_checker.rs#L136), which [calls the prepare method on the mutator](https://github.com/mmtk/mmtk-core/blob/master/src/scheduler/gc_work.rs#L91), which in turn calls [the `prepare_func` for that plan](https://github.com/mmtk/mmtk-core/blob/master/src/plan/mutator_context.rs#L102). For most plans (with the exception of MarkSweep), this is set to the `unreachable_prepare_func` stub, which [triggers a panic](https://github.com/mmtk/mmtk-core/blob/master/src/plan/mutator_context.rs#L24).

**Comment by qinsoon** [comment]
I think sanity GC should do something like the code below in `SanityPrepare`
https://github.com/mmtk/mmtk-core/blob/42754a5f23fdb513039d7f07e52014ded42c98bf/src/scheduler/gc_work.rs#L62-L67

https://github.com/mmtk/mmtk-core/blob/42754a5f23fdb513039d7f07e52014ded42c98bf/src/util/sanity/sanity_checker.rs#L135-L138

**Comment by angussidney** [comment]
As a quick test, I tried removing the following sections of code, and the Sanity GC worked fine on the Immix, SemiSpace, MarkSweep and MarkCompact plans.

https://github.com/mmtk/mmtk-core/blob/master/src/util/sanity/sanity_checker.rs#L135-L142

https://github.com/mmtk/mmtk-core/blob/master/src/util/sanity/sanity_checker.rs#L160-L167

**Comment by qinsoon** [comment]
> As a quick test, I tried removing the following sections of code, and the Sanity GC worked fine on the Immix, SemiSpace, MarkSweep and MarkCompact plans.
> 
> https://github.com/mmtk/mmtk-core/blob/master/src/util/sanity/sanity_checker.rs#L135-L142
> 
> https://github.com/mmtk/mmtk-core/blob/master/src/util/sanity/sanity_checker.rs#L160-L167

In Java MMTk there isn't mutator/collector prepare/release for sanity GC, and there was no mutator/collector prepare/release when it was ported to Rust: https://github.com/mmtk/mmtk-core/blob/96855d287fe5ea789a532f347d6ee37e6679c71f/src/util/sanity/sanity_checker.rs. @wenyuzhao added those when work packet was introduced: https://github.com/mmtk/mmtk-core/blame/66dbdce4e3b392c260b9f4601764b53379877eed/src/util/sanity/sanity_checker.rs. 

@wenyuzhao Do you remember why we would need those code?

**Comment by wenyuzhao** [comment]
> > As a quick test, I tried removing the following sections of code, and the Sanity GC worked fine on the Immix, SemiSpace, MarkSweep and MarkCompact plans.
> > https://github.com/mmtk/mmtk-core/blob/master/src/util/sanity/sanity_checker.rs#L135-L142
> > https://github.com/mmtk/mmtk-core/blob/master/src/util/sanity/sanity_checker.rs#L160-L167
> 
> In Java MMTk there isn't mutator/collector prepare/release for sanity GC, and there was no mutator/collector prepare/release when it was ported to Rust: https://github.com/mmtk/mmtk-core/blob/96855d287fe5ea789a532f347d6ee37e6679c71f/src/util/sanity/sanity_checker.rs. @wenyuzhao added those when work packet was introduced: https://github.com/mmtk/mmtk-core/blame/66dbdce4e3b392c260b9f4601764b53379877eed/src/util/sanity/sanity_checker.rs.
> 
> @wenyuzhao Do you remember why we would need those code?

No i think it's not necessary. I probably directly copied this from the normal GC tracing work packets.
