### ISSUE TITLE
Move trace_object() to SFT

### ISSUE THREAD

**Issue by qinsoon** [mmtk/mmtk-core#110]
As raised in https://github.com/mmtk/mmtk-core/pull/108#discussion_r444670594, invoking `initialize_header()` from a `Space` trait object would result in dynamic dispatching in the fast path. We can move `initialize_header()` to `SFT`, this would solve the problem.

**Comment by qinsoon** [comment]
We want to do a similar refactoring for `trace_object()` as well.

**Comment by qinsoon** [comment]
`initialize_header()` is in `SFT`. However, we cannot easily move `trace_object()` to `SFT` without further refactoring. `SFT` is a trait object, which means its methods need to be simple. However, `trace_object()` is a generic method (with `T: TransitiveClosure`), which is not simple. We need refactoring.

**Comment by steveblackburn** [comment]
I'd like to up the priority on this.   Perhaps this can be done as part of the next bugfix/cleanup release.

**Comment by qinsoon** [comment]
> `trace_object()` has two type parameters, but the types themselves are never explicitly used in the function body. So they can be replaced with `impl TransitiveClosure` and `impl CopyContext`. They are semantically equivalent, but less verbose. `impl SomeTrait` means the concrete type of the parameter can still be inferred at compile time, but we just don't mention the concrete type name. Therefore it still has the performance advantage (including opportunities to inline) of generic parameters.
> 
> ```diff
> diff --git a/src/policy/copyspace.rs b/src/policy/copyspace.rs
> index 77e75321..d6ad9154 100644
> --- a/src/policy/copyspace.rs
> +++ b/src/policy/copyspace.rs
> @@ -182,12 +182,12 @@ impl<VM: VMBinding> CopySpace<VM> {
>      }
>  
>      #[inline]
> -    pub fn trace_object<T: TransitiveClosure, C: CopyContext>(
> +    pub fn trace_object(
>          &self,
> -        trace: &mut T,
> +        trace: &mut impl TransitiveClosure,
>          object: ObjectReference,
>          semantics: AllocationSemantics,
> -        copy_context: &mut C,
> +        copy_context: &mut impl CopyContext,
>      ) -> ObjectReference {
>          trace!("copyspace.trace_object(, {:?}, {:?})", object, semantics,);
>          debug_assert!(
> ```

I think `impl Trait` is considered the same as generic type parameters in terms of object safety. That means if we would like to use a trait object, its method cannot use `<T>` as well as `a: impl Trait` as parameters.
