### ISSUE TITLE
Any plan to support C++?

### ISSUE THREAD

**Issue by harry75369** [mmtk/mmtk-core#1113]
# C++ Support

C++ standard lib is easy to use, however, it often leads to memory issues and thus low performance. The most common pattern I have recognized is that the frequent allocs and deallocs of small memory blocks.

I'm wondering if using mmtk could help this problem. I don't want to implement my own standard lib or use something like Boost. And I don't want even to change my programming habits for writing C++ code.

I have no idea if mmtk could solve this problem, and how to solve it. At first it should be usable by C++ users. And then maybe the standard lib's allocator be replaced by mmtk seaminglessly?

So is there any plan to support C++?

**Comment by wks** [comment]
See: https://github.com/mmtk/mmtk-core/issues/664

**Comment by harry75369** [comment]
The problem I encountered is the performance issue I just mentioned (which is due to poor memory management in C++). I'm looking for solutions other than refactoring our code. And after watching your [youtube](https://www.youtube.com/watch?v=0mldpiYW1X4) introduction, I realized that MMTK may be helpful, if we can utilize its underlying memory manager to automatically solve the problem of frequent memory alloc/dealloc of small memory blocks.

For example, we used to process a lot of temporary std::string objects in C++. They are frequently alloced and dealloced. We are obliged to manually implement a memory pool and use std::string_view instead. It would be very useful if such tasks could be automatically solved.

BTW, similar examples are very common when developing C++ applications if we use C++ standard library. C won't have this problem because you have to implement everything all on your own. And this problem doesn't exist if we do not use C++ standard library. But we do, and a lot of C++ users do.

> Hi! Thanks for your interest in MMTk. I'm not quite sure what you want from MMTk? There are future plans to make it a drop-in replacement for the [Boehm-Demers-Weiser conservative collector](https://github.com/ivmai/bdwgc). Does that answer your question? Or were you imagining MMTk being used for something more subtle such as an arena allocator, etc?

The [Boehm-Demers-Weiser conservative collector](https://github.com/ivmai/bdwgc) also seems interesting and I'll take a look. Thanks. But even you finished the drop-in replacement of bdwgc, I'm still wondering how this would help for my problem. Or is it too low-level for my problem?

**Comment by k-sareen** [comment]
I think for the use-case you have described (many small object allocations that are temporary), an arena allocator would suffice. Since they are temporary objects, you can throw the arena out when you are done with them (assuming the objects have similar lifetimes). There are many implementations of arena allocators for C++. While this is something MMTk would likely support in the future, we currently do not have a roadmap or estimate when this would be implemented given we are a small team.

For what it's worth, BDW GC is quite different from an arena allocator. It aims to be an actual GC for C/C++ applications which may-or-may-not be what you want.

**Comment by harry75369** [comment]
> I think for the use-case you have described (many small object allocations that are temporary), an arena allocator would suffice. Since they are temporary objects, you can throw the arena out when you are done with them (assuming the objects have similar lifetimes). There are many implementations of arena allocators for C++. While this is something MMTk would likely support in the future, we currently do not have a roadmap or estimate when this would be implemented given we are a small team.

I see. Thank you for the advice!

> For what it's worth, BDW GC is quite different from an arena allocator. It aims to be an actual GC for C/C++ applications which may-or-may-not be what you want.

C++ has no built-in GC system, however, in C++ we can utilize the constructor/decontructor to simulate the developer experience as if there is a GC because the decontructor will execute deallocators to clean memory when the temp object is out of scope. And this is how std::string/std::vector/... works. But this leads to a local maxima. The performant application should reach global maxima by determining exactly when the memory should be allocated and when should be deallocated (because compared to CPU operations, memory operations are much more expensive). And this is exactly what GC should consider, right? The deallocation shouldn't be determined by just running out of scopes.

And the use of a custom allocator seems the only way to implement a GC system in C++, in my point of view. If so, I'm glad that if MMTK for C++ could be implemented this way so that I could use it directly in my daily C++ projects. Put it another way, could MMTK be treated as a more advanced version of arena allocator?

**Comment by k-sareen** [comment]
> C++ has no built-in GC system ...

Yes. But we can still use a conservative GC by hijacking `malloc` and `free` like how the BDW GC does. "Conservative" here means that the language does not provide enough information for the GC to figure out if a particular thing in memory is a pointer or an integer or some other data. As a side-effect, this means the GC cannot move objects.

> Put it another way, could MMTK be treated as a more advanced version of arena allocator?

Yes and no. Arena allocation, by definition, is extremely specialized. It is designed for allocating many temporary objects with similar lifetimes together and then throwing away the arena to avoid freeing them manually or tracing/reference counting the objects to figure out which ones are alive. So it's really efficient. But this is only possible to use for some workloads. MMTk, on the other hand, would be more general, though we may still provide an arena allocation API but the specifics are not clear right now. Being general means that it may not be as good as an arena allocator for use cases where you can use an arena allocator, but it also means that you probably have a better memory management system for many more types of programs where an arena allocator does not make sense.

**Comment by harry75369** [comment]
Thanks for the explanations. Hopes MMTK will support C++ in the future. Not necessarily an arena version. The general version will be quite useful for general use cases. A high-performance GC system is very helpful for implementing a large C++ based system correctly and efficiently.

You may close this issue as it is somewhat duplicated with https://github.com/mmtk/mmtk-core/issues/664
