### ISSUE TITLE
Work packet cleanup

### ISSUE THREAD

**Issue by qinsoon** [mmtk/mmtk-core#172]
From unresolved comments in https://github.com/mmtk/mmtk-core/pull/136:
* [x] Allocator mapping for GenCopy is incorrect. 
* [x] `TransitiveClosure` and `TraceLocal` can be removed. 
* [x] We may want a general bucket map such as `Map<Stage, WorkBucket>`.

**Comment by k-sareen** [comment]
https://github.com/mmtk/mmtk-core/pull/607
