### ISSUE TITLE
Allow frequent byte-level triggering of collection/analysis

### ISSUE THREAD

**Issue by qinsoon** [mmtk/mmtk-core#188]
We would like a mechanism that allows us to trigger collection/analysis on byte-level granularity. It should be zero overhead when disabled and can be enabled at run-time. This will replace the current stress test triggering, and will be used for both sanity analysis and stress GC. 

This is the proposed implementation by Steve.
1. The fastpath is unchanged. However, the cursor/limit (e.g. for bump pointer allocator) should be set to masked values if enabled so that 1) it always fails the limit check in the fastpath and goes to the slowpath, and 2) we can retrieve the real cursor/limit values from the masked values. 
2. In the slowpath, we maintain a counter for cumulative bytes allocated since last collection/analysis. We may maintain separate counters for sanity and stress GC. 
3. If the counter is not larger than a defined threshold (by command line options), we retrieve the real cursor/limit values and do allocation. 
4. If the counter is larger than the threshold, we trigger a sanity analysis or a stress GC, depending on the counter.
   * For sanity analysis, when we finish the sanity analysis, we do normal allocation.

**Comment by k-sareen** [comment]
Should be closed with #227 #248?
