### ISSUE TITLE
Assertion failure when stack scanning mutators

### ISSUE THREAD

**Issue by k-sareen** [mmtk/mmtk-core#211]
I've been encountering what I think is an MMTk bug. Specifically, at small values of `MMTK_SANITY_FACTOR` on this branch [1], the bug is consistently reproducible. The bug is an assertion failure when the coordinator starts its `StopMutators` work packet [2]. Essentially, it seems like a number of stacks have already been scanned before the coordinator starts. Unfortunately I have not been able to debug the root cause properly. Note that this could also be a bug in my implementation of byte-level sanity.  

I have been using two test cases: DaCapo's fop and fannkuch-redux [3] from the Computer Language Benchmarks Game.

\[1]: https://github.com/k-sareen/mmtk-core/tree/byte-level-sanity
[2]: https://github.com/mmtk/mmtk-core/blob/b9dc151/src/scheduler/gc_works.rs#L161
[3]: https://salsa.debian.org/benchmarksgame-team/benchmarksgame/-/blob/master/bencher/programs/fannkuchredux/fannkuchredux.java

Error:
```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `0`', /home/$USER/mmtk-core/src/scheduler/gc_works.rs:161:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/1f5bc176b0e54a8e464704adcd7e571700207fe9/library/core/src/panicking.rs:92:14
   2: <mmtk::scheduler::gc_works::StopMutators<E> as mmtk::scheduler::work::GCWork<<E as mmtk::scheduler::gc_works::ProcessEdgesWork>::VM>>::do_work
             at /home/$USER/mmtk-core/src/scheduler/gc_works.rs:161:13
   3: <W as mmtk::scheduler::work::Work<mmtk::mmtk::MMTK<VM>>>::do_work
             at /home/$USER/mmtk-core/src/scheduler/work.rs:33:9
   4: mmtk::scheduler::work::Work::do_work_with_stat
             at /home/$USER/mmtk-core/src/scheduler/work.rs:14:9
   5: mmtk::scheduler::scheduler::Scheduler<C>::process_coordinator_work
             at /home/$USER/mmtk-core/src/scheduler/scheduler.rs:161:9
   6: mmtk::scheduler::scheduler::Scheduler<C>::wait_for_completion
             at /home/$USER/mmtk-core/src/scheduler/scheduler.rs:174:21
   7: mmtk::plan::controller_collector_context::ControllerCollectorContext<VM>::run
             at /home/$USER/mmtk-core/src/plan/controller_collector_context.rs:73:13
   8: mmtk::mm::memory_manager::start_control_collector
             at /home/$USER/mmtk-core/src/mm/memory_manager.rs:42:5
   9: start_control_collector
             at /home/$USER/mmtk-openjdk/mmtk/src/api.rs:35:5
  10: _ZL19thread_native_entryP6Thread
  11: start_thread
  12: __clone
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
```

**Comment by qinsoon** [comment]
Is this reproducible in the master branch (bb9fd6c9acfd685af729ca6be9a9d3cb9b26435f)? Exactly which assertion failed? Are you testing with OpenJDK binding?

**Comment by k-sareen** [comment]
I have encountered the bug via stress testing semi space once. But I can't reproduce it consistently (or under reasonable time constraints) due to stress testing taking a lot of time. The above branch somewhat stresses the scheduling system as a side effect as it generates a lot of `ScheduleSanityGC` work packets, but without the overhead of performing a gc everytime. Yes, I'm using the OpenJDK binding.

Ah sorry I forgot to link the exact line. I've edited the original issue with the line where the assertion fails.

**Comment by k-sareen** [comment]
I've been debugging this and it seems like there's a race condition on accessing the variable `BasePlan.scanned_stacks` in `ScanStackRoot` work packet.
#### Expected
```
    mutator OpaquePointer(0x7f18a821b000) old scanned_stacks = 0, new scanned_stacks = 1
    mutator OpaquePointer(0x7f18a801a800) old scanned_stacks = 1, new scanned_stacks = 2
    mutator OpaquePointer(0x7f18a801a800) old scanned_stacks = 2, new scanned_stacks = 3
    mutator OpaquePointer(0x7f18a801a800) old scanned_stacks = 3, new scanned_stacks = 0
    mutator OpaquePointer(0x7f18a8218800) old scanned_stacks = 0, new scanned_stacks = 1
    mutator OpaquePointer(0x7f18a8218800) old scanned_stacks = 1, new scanned_stacks = 2
    mutator OpaquePointer(0x7f18a821b000) old scanned_stacks = 2, new scanned_stacks = 3
    mutator OpaquePointer(0x7f18a821b000) old scanned_stacks = 3, new scanned_stacks = 0
```
#### Actual
```
    mutator OpaquePointer(0x7f18a8218800) old scanned_stacks = 0, new scanned_stacks = 1
    mutator OpaquePointer(0x7f18a821b000) old scanned_stacks = 1, new scanned_stacks = 2
    mutator OpaquePointer(0x7f18a821b000) old scanned_stacks = 2, new scanned_stacks = 3
    mutator OpaquePointer(0x7f18a821b000) old scanned_stacks = 3, new scanned_stacks = 0
    mutator OpaquePointer(0x7f18a8218800) old scanned_stacks = 3, new scanned_stacks = 4
    mutator OpaquePointer(0x7f18a801a800) old scanned_stacks = 0, new scanned_stacks = 1
    mutator OpaquePointer(0x7f18a801a800) old scanned_stacks = 1, new scanned_stacks = 2
```
The expected value comes from the `ScanStackRoot` work packet that was ran just before the one that caused the error. Note the value of `old scanned_stacks`.

**Comment by k-sareen** [comment]
So I can think of a few possible solutions:

1. Wrap `scanned_stacks` in a mutex. Pretty simple solution that ensures correctness, however it would perform terribly given the locking nature.
2. Read `scanned_stacks` in the guard condition so as to have an updated value. Change the guard condition to `>=` instead of a strict `==` and instead of setting to 0, subtract the number of mutators using `fetch_sub()`. Allows for the most flexibility and does not sacrifice performance but I'm not sure of what the semantics of `scanned_stacks` is so this solution could be incorrect. Should threads be waiting on the value to be set to 0 before they continue again, since it seems like each mutator thread is scanned twice as per logs?
3. Have the entire code that uses `scanned_stacks` to be in a transactional loop wherein we use a local value and try to update it at the end, and retry if someone had updated the variable while we were using it. However it is quite likely that each loop iteration may fail and hence it's not as performant.

@wenyuzhao since you wrote the code, do you have any thoughts on the matter?

**Comment by javadamiri** [comment]
> I've been debugging this and it seems like there's a race condition on accessing the variable `BasePlan.scanned_stacks` in `ScanStackRoot` work packet.
> 
> #### Expected
> ```
>     mutator OpaquePointer(0x7f18a821b000) old scanned_stacks = 0, new scanned_stacks = 1
>     mutator OpaquePointer(0x7f18a801a800) old scanned_stacks = 1, new scanned_stacks = 2
>     mutator OpaquePointer(0x7f18a801a800) old scanned_stacks = 2, new scanned_stacks = 3
>     mutator OpaquePointer(0x7f18a801a800) old scanned_stacks = 3, new scanned_stacks = 0, number_of_mutators = 3
>     mutator OpaquePointer(0x7f18a8218800) old scanned_stacks = 0, new scanned_stacks = 1
>     mutator OpaquePointer(0x7f18a8218800) old scanned_stacks = 1, new scanned_stacks = 2
>     mutator OpaquePointer(0x7f18a821b000) old scanned_stacks = 2, new scanned_stacks = 3
>     mutator OpaquePointer(0x7f18a821b000) old scanned_stacks = 3, new scanned_stacks = 0, number_of_mutators = 3
> ```
> 
> #### Actual
> ```
>     mutator OpaquePointer(0x7f18a8218800) old scanned_stacks = 0, new scanned_stacks = 1
>     mutator OpaquePointer(0x7f18a821b000) old scanned_stacks = 1, new scanned_stacks = 2
>     mutator OpaquePointer(0x7f18a821b000) old scanned_stacks = 2, new scanned_stacks = 3
>     mutator OpaquePointer(0x7f18a821b000) old scanned_stacks = 3, new scanned_stacks = 0, number_of_mutators = 3
>     mutator OpaquePointer(0x7f18a8218800) old scanned_stacks = 3, new scanned_stacks = 4
>     mutator OpaquePointer(0x7f18a801a800) old scanned_stacks = 0, new scanned_stacks = 1
>     mutator OpaquePointer(0x7f18a801a800) old scanned_stacks = 1, new scanned_stacks = 2
> ```
> 
> The expected value comes from the `ScanStackRoot` work packet that was ran just before the one that caused the error. Note the value of `old scanned_stacks`. (The mutator values are irrelevant; they were there to help my instrumentation).
> 
> Offending line: https://github.com/mmtk/mmtk-core/blob/b9dc151/src/scheduler/gc_works.rs#L246
> I think the race condition happens on the above line. A thread can be interrupted and context switched before the `old + 1` is checked against the number of mutators. In the above example, a thread increments `scanned_stacks` to 3 and before it can check against the number of mutators, another thread interrupts it and then updates the value to 4. Since `4 != 3`, it does not reset the count of `scanned_stacks`. Returning back to the original thread, the old value is still 3 and hence it resets the `scanned_stacks` count to 0.

I don't quite understand why the transition from 3 to 4 occurs.
I assume the thread that performs the 3 to 0 transition is doing the last job from a number of stack_scan works.
Why is the other thread (3to4) being created/run at all?

**Comment by k-sareen** [comment]
I think it was due to the bug in how I was calling sanity, however, I've encountered this bug before while stress testing

**Comment by k-sareen** [comment]
Possibly. Unfortunately stress takes ages to run. I'm quite confident however that at least the race condition for updating the scanned_stack variable has been fixed, though.
