### ISSUE TITLE
OpenJDK binding slowdown for antlr after PR #223

### ISSUE THREAD

**Issue by qinsoon** [mmtk/mmtk-core#226]
There was huge slowdown for `antlr` (from 1.09 to 1.31) for the OpenJDK binding in [the performance regression CI](https://github.com/mmtk/mmtk-core/runs/1851961848) after https://github.com/mmtk/mmtk-core/pull/223 was merged. There was no slowdown for other benchmarks, and no slowdown for the JikesRVM binding for all benchmarks (https://www.mmtk.io/ci-perf-result/master/jikesrvm_semispace_history.html). So this could possibly be noisy data. I don't suggest spending time investigating this. We will have a few PRs to merge in the following days - we can keep an eye on their perf runs.

Run ID: 2021-02-08-Mon-155114 in https://www.mmtk.io/ci-perf-result/master/openjdk_semispace_history.html

**Comment by steveblackburn** [comment]
We need to *thoroughly* performance-analyze this PR with the generational collector (ie to test the performance in the write barrier).   We should back out the PR if necessary.   I have asked @wenyuzhao to do a thorough analysis using his implementation and analysis setup.

**Comment by qinsoon** [comment]
We measured a few commits around https://github.com/mmtk/mmtk-core/pull/223. It shows that we do not have a performance regression as shown in the CI, which means the data in the CI is mostly due to noise. 
![WX20210309-154119](https://user-images.githubusercontent.com/1664709/110410555-ee62f800-80ed-11eb-95ed-00703d3e87f4.png)

https://github.com/mmtk/mmtk-core/issues/261 tracks the issue of performance overhead of side metadata in GenCopy.
