### ISSUE TITLE
Potential bug in dzmmap

### ISSUE THREAD

**Issue by javadamiri** [mmtk/mmtk-core#244]
The use of `MAP_FIXED` flag in the `dzmmap` functions means we overwrite any previous mapping that may overlap with our current request:

https://github.com/mmtk/mmtk-core/blob/a4110d917c758b5261eeefbc6e2b00a58233e215/src/util/memory.rs#L15

Although it is very unlikely to happen in 64-bits targets, it is still possible.
For example, we do not know how various `malloc` implementations use the address space, and we may overwrite their mappings.

An alternative is to remove the `MAP_FIXED` flag and compare the result of mmap with our requested starting address.
AFAIK, they will be the same if there is no overlaps.

**Comment by qinsoon** [comment]
This is done in https://github.com/mmtk/mmtk-core/pull/296. All uses of `MAP_FIXED` in mmtk-core is replaced with `MAP_FIXED_NOREPLACE`.
