### ISSUE TITLE
Side metadata consistency check

### ISSUE THREAD

**Issue by caizixian** [mmtk/mmtk-core#274]
We should add some consistency checks (perhaps during runtime) for side metadata specs. For example, we should check that two metadata specs don't overlap.

**Comment by qinsoon** [comment]
For MallocSpace, I have used hash sets to verify results from side metadata. It is only enabled for debug builds. Maybe we can move this to the side metadata implementation.
https://github.com/mmtk/mmtk-core/blob/141639ab452cc464b8a41f55356e9dc945066b1a/src/policy/mallocspace/metadata.rs#L32

**Comment by javadamiri** [comment]
> For MallocSpace, I have used hash sets to verify results from side metadata. It is only enabled for debug builds. Maybe we can move this to the side metadata implementation.
> https://github.com/mmtk/mmtk-core/blob/141639ab452cc464b8a41f55356e9dc945066b1a/src/policy/mallocspace/metadata.rs#L32

I think we can guard these checks under the `extreme_assertions` feature.
Let me know if you have any other ideas

**Comment by qinsoon** [comment]
> > For MallocSpace, I have used hash sets to verify results from side metadata. It is only enabled for debug builds. Maybe we can move this to the side metadata implementation.
> > https://github.com/mmtk/mmtk-core/blob/141639ab452cc464b8a41f55356e9dc945066b1a/src/policy/mallocspace/metadata.rs#L32
> 
> I think we can guard these checks under the `extreme_assertions` feature.
> Let me know if you have any other ideas

If you think it is helpful to have those checks for side metadata (not only for side metadata in marksweep), we can move them to side metadata from marksweep and guard with extreme_assertions. Otherwise, just keeping them as they are would be fine.

**Comment by qinsoon** [comment]
I assume we can close this issue. @javadamiri
