### ISSUE TITLE
Make object forwarding VM specific

### ISSUE THREAD

**Issue by qinsoon** [mmtk/mmtk-core#277]
Currently the forwarding code is in mmtk-core. We figure out where we can store the forwarding pointer from the `GC_BYTE_OFFSET`. For https://github.com/mmtk/mmtk-core/issues/276, we may need to remove `GC_BYTE_OFFSET`. That means we may need to make object forwarding VM-specific.

**Comment by qinsoon** [comment]
Related issues/PRs:
* https://github.com/mmtk/mmtk-core/pull/975
* https://github.com/mmtk/mmtk-core/issues/1030

**Comment by steveblackburn** [comment]
Closing because it is covered by #1030.

See [this comment](https://github.com/mmtk/mmtk-core/issues/1030#issuecomment-1841986455)
