### ISSUE TITLE
Check duplicate edges in the debug build

### ISSUE THREAD

**Issue by javadamiri** [mmtk/mmtk-core#291]
Duplicate edges break our invariant that each edge is only scanned once, and requires adding atomic operation to our fastpath (e.g. to `process_edge`), which is wrong and has high overhead.
Following the bug we found when debugging issue #12 from `mmtk-openjdk`, we concluded that we need assertions to check whether any duplicate edges are created.
As these assertions are expensive, we will only put them in the debug build.

**Comment by javadamiri** [comment]
We can probably use one side metadata bit per address to keep track of edges.

**Comment by qinsoon** [comment]
As Zixian suggested in https://mmtk.zulipchat.com/#narrow/stream/262674-mmtk-openjdk/topic/Issue.20.2312/near/234088641, we could add a feature `extreme_assertions` to allow expensive assertions such as this.
