### ISSUE TITLE
Rust binary literals

### ISSUE THREAD

**Issue by wks** [mmtk/mmtk-core#340]
When defining bit constants, we have code like the following:

From `mmtk-core/src/util/forwarding_words.rs`:
```rust
// ...00
const FORWARDING_NOT_TRIGGERED_YET: u8 = 0;
// ...10
const BEING_FORWARDED: u8 = 2;
// ...11
const FORWARDED: u8 = 3;
// ...11
const FORWARDING_MASK: u8 = 3;
```

Obviously the code is ported from JikesRVM (See `JikesRVM/MMTk/src/org/mmtk/utility/ForwardingWord.java`).

But Rust has binary literals. We should have just written the following code instead:

```rust
const FORWARDING_NOT_TRIGGERED_YET: u8 = 0b00;
const BEING_FORWARDED: u8 = 0b10;
const FORWARDED: u8 = 0b11;
const FORWARDING_MASK: u8 = 0b11;
```

and preferably align the constants bit by bit to avoid bugs:

```rust
const FORWARDING_NOT_TRIGGERED_YET: u8 = 0b00;
const BEING_FORWARDED: u8              = 0b10;
const FORWARDED: u8                    = 0b11;
const FORWARDING_MASK: u8              = 0b11;
```

Then the comments like `// ... 00`, `// ... 10`, etc. are completely redundant.

**Comment by qinsoon** [comment]
This was fixed in https://github.com/mmtk/mmtk-core/pull/440.
