### ISSUE TITLE
Unable to build with nightly specified in mmtk-dev-env Dockerfile

### ISSUE THREAD

**Issue by osa1** [mmtk/mmtk-core#394]
If I follow the mmtk-dev-env Dockerfile for Ubuntu on my Ubuntu 20.04 system I'm unable to build `mmtk` crate referenced in `mmtk-openjdk/mmtk/Cargo.toml` because the toolchain specified in the Dockerfile (nightly-2020-12-20) is too old for mmtk-core:

```
error[E0599]: no variant or associated item named `OutOfMemory` found for enum `ErrorKind` in the current scope
  --> /home/omer/.cargo/git/checkouts/mmtk-core-3306bdeb8eb4322b/f50ac55/src/util/memory.rs:91:20
   |
91 |         ErrorKind::OutOfMemory => {
   |                    ^^^^^^^^^^^ variant or associated item not found in `ErrorKind`

error: aborting due to previous error
```

If I use the latest nightly I'm able to build `mmtk_openjdk`.

**Comment by qinsoon** [comment]
Thanks for the issue. The docker file is out-of-date (it should be using nightly-2021-05-12). I moved this issue to mmtk-core. I will update it and will add a workflow in the core CI to make sure mmtk can always build with the docker.

**Comment by qinsoon** [comment]
This is fixed. And now we have a workflow to check if we can build mmtk-core with the mmtk-dev-env image.
