### ISSUE TITLE
MallocSpace maps side metadata based on cell address but set bit based on object reference

### ISSUE THREAD

**Issue by qinsoon** [mmtk/mmtk-core#405]
`MallocSpace` maps side metadata based on the address returned from `malloc` (the cell address).
https://github.com/mmtk/mmtk-core/blob/c4c2dcd8ee2470f94aea5cfedafa63abf3497fcd/src/policy/mallocspace/global.rs#L204

But when it sets bit in `initialize_object_metadata()`, it uses the object reference.
https://github.com/mmtk/mmtk-core/blob/c4c2dcd8ee2470f94aea5cfedafa63abf3497fcd/src/policy/mallocspace/global.rs#L76-L77

This could lead to a segfault if the cell address and the object reference are not in the same chunk. E.g, malloc returns us the last few bytes in a chunk, but the object reference is the start of the next chunk.

**Comment by k-sareen** [comment]
Close?

**Comment by qinsoon** [comment]
Yeah. This issue has been fixed in #434.
