### ISSUE TITLE
on_closure_end() is inconsistent with our API design

### ISSUE THREAD

**Issue by qinsoon** [mmtk/mmtk-core#407]
Our bidirectional interface includes 1. a set of API functions (`mmtk::memory_manager`, VM->MMTk), and 2. a set of VM traits (`mmtk::vm`, MMTk->VM).

However, we recently added `on_closure_end()` to API functions (https://github.com/mmtk/mmtk-core/pull/375), but it takes a closure and MMTk invokes the closure. Logically it should be part of MMTk->VM interface, and belongs to the VM traits.

https://github.com/mmtk/mmtk-core/blob/093da769a71067dcd4f37db6f453213e7dace660/src/memory_manager.rs#L439

I think we can move it to the `VMCollection` trait, and rename it to `vm_closure_end()`, making it a sibling of `vm_release()`.
https://github.com/mmtk/mmtk-core/blob/2b55f89622dcc4c293bb472c634165e2ce7c2c5c/src/vm/collection.rs#L73

**Comment by k-sareen** [comment]
Closed with: https://github.com/mmtk/mmtk-core/commit/844aa0ea5c8c6c4eec6d1336495a14dbcd025718
