### ISSUE TITLE
Use sane testing CI defaults

### ISSUE THREAD

**Issue by k-sareen** [mmtk/mmtk-core#424]
Currently the default CI heap values is 500Mb for OpenJDK (for example). A benchmark such as `fop` does not even require more than 250Mb to run with a NoGC. Hence, largely these CI tests don't actually give us confidence in the correctness of our GCs since they are not actively stressing them. We should also be testing more benchmarks instead of the 5-6 we have currently.

On a similar note, we should ideally start migrating to the newer running scripts to drive the test CI as well.

I am making this issue in core instead of the bindings as this affects all bindings in general.

**Comment by qinsoon** [comment]
I thought about using the new running script. I think we may need a feature from the running script to do this: abort on failed runs. @caizixian

**Comment by qinsoon** [comment]
Done in https://github.com/mmtk/mmtk-openjdk/pull/263.
