### ISSUE TITLE
NoGC is slow with DaCapo Chopin `tomcat`

### ISSUE THREAD

**Issue by caizixian** [mmtk/mmtk-core#439]
Core: 6bd61aab
OpenJDK binding: https://github.com/mmtk/mmtk-openjdk/tree/648bb27f4bb5c84a83f74fda1d699514548cf663

Set the features of `mmtk` to be `["perf_counter", "nogc_lock_free", "nogc_no_zeroing"]`.
In addition, `memory::zero(res.start, bytes)` is removed from `Space::acquire` to avoid double zeroing. See also #433 
Set `MAX_PHASES` to `1 << 14` in `statistics` to prevent the counter value array from overflowing. Certain benchmarks need many GCs when given small heap sizes.

We can see from the plots that for `tomcat`, NoGC is 13% slower than Epsilon, and executes about 5% more instructions.

![image](https://user-images.githubusercontent.com/2891235/132333490-3f42d29d-94f1-4d10-bbee-e82c90adec22.png)
![image](https://user-images.githubusercontent.com/2891235/132333521-1bbed005-bb29-4f91-97e6-8191d5235936.png)
![image](https://user-images.githubusercontent.com/2891235/132333529-4749af9c-e643-41b0-9390-981c3a1c694c.png)
![image](https://user-images.githubusercontent.com/2891235/132333544-2acdfc51-9468-4c70-aa87-91f0dca96b0f.png)
![image](https://user-images.githubusercontent.com/2891235/132333557-17d48f84-e7df-4327-9f35-f232847e9107.png)
![image](https://user-images.githubusercontent.com/2891235/132333629-1a36e6e5-4d49-4b9c-8023-2df80d3c646b.png)

**Comment by qinsoon** [comment]
Zixian suggested that if we use lock free immortal space, there should be no performance issue.
