### ISSUE TITLE
Cleanup chunk-sweeping methods of `MallocSpace`

### ISSUE THREAD

**Issue by caizixian** [mmtk/mmtk-core#485]
The two methods, `sweep_chunk_mark_on_side` and `sweep_chunk_mark_in_header`, are long and hard to understand.
The former is 200 lines long, which is really hard to read, and the two methods are quite similar structure-wise.

**Comment by k-sareen** [comment]
Yeah fair -- it is very inelegant currently. Once we have a linear scan interface then we should revisit this as that would make life easier
