### ISSUE TITLE
Statistics sometimes include data for ReleaseCollector when no GC is recorded during harness

### ISSUE THREAD

**Issue by qinsoon** [mmtk/mmtk-core#503]
When running benchmarks with probes, statistics are recorded during `harness_begin()` and `harness_end()`. When there is no GC between `harness_begin()` and `harness_end()`, we expect to see no statistics, such as
```
============================ MMTk Statistics Totals ============================
GC      time.other      time.stw        total-work.count        total-work.time.min     total-work.time.total   total-work.time.max
0       7043.49 0.00    0       inf     0.00    -inf
Total time: 7043.49 ms
------------------------------ End MMTk Statistics -----------------------------
```

However, sometimes, statistics include data for ReleaseCollector work, such as
```
============================ MMTk Statistics Totals ============================
GC      time.other      time.stw        total-work.time.max     total-work.time.min     work.ReleaseCollector.time.total        work.ReleaseCollector.time.max  total-work.time.total   work.ReleaseCollector.time.min  total-work.count        work.ReleaseCollector.count
0       7043.75 0.00    742.00  742.00  742.00  742.00  742.00  742.00  1       1
Total time: 7043.75 ms
------------------------------ End MMTk Statistics -----------------------------
```

I observed this behavior when running benchmarks with 339640fe1eaf8f7aa0251c94553ef71e0c8dcf28. This could be an old bug. The command line I used (with a release build):
```
MMTK_PLAN=SemiSpace /home/yilin/ci-perf-kit/build/jdk-mmtk-master/jdk/bin/java -XX:MetaspaceSize=500M -XX:+DisableExplicitGC -server -XX:-TieredCompilation -Xcomp -XX:+UseThirdPartyHeap -Dprobes=RustMMTk -Djava.library.path=/home/yilin/ci-perf-kit/probes/native/rust_mmtk -Xms849M -Xmx849M -cp /usr/share/benchmarks/dacapo/dacapo-evaluation-git-69a704e.jar:/home/yilin/ci-perf-kit/probes/rust_mmtk/java:/home/yilin/ci-perf-kit/probes/probes.jar Harness -c probe.DacapoChopinCallback -n 3 jme
```
The incorrect statistics appeared in 3 runs out of 40 runs.

I guess there is a concurrency bug and the `ReleaseCollector` work from last GC before `harness_begin()` is somehow incorrectly counted into the statistics we collect. If this is true, that means with GCs, it is possible that we may still incorrectly include the statistics of the `ReleaseCollector` work from the last GC before we actually start to measure. However, the severity of the issue is low in my opinion, as it appears infrequently (3/40), and only includes 1 `ReleaseCollector` packet in my observation -- this should have minor impact on the average number.

**Comment by qinsoon** [comment]
This is caused by https://github.com/mmtk/mmtk-core/issues/600.

Basically the `ReleaseCollector` work we see in the statistics is scheduled in a previous GC. As work in `local_work_bucket` does not prevent new buckets being activated, the `ReleaseCollector` stays in some GC workers local bucket, while further buckets are opened and GC progresses/finishes. The GC workers execute `ReleaseCollector` after GC is done, and after we call `harness_begin()`.

**Comment by k-sareen** [comment]
Presumably we close this since #600 has been closed?
