### ISSUE TITLE
Handling Out of Memory errors

### ISSUE THREAD

**Issue by k-sareen** [mmtk/mmtk-core#534]
Currently MMTk's contract with the VM expects that the VM crashes or aborts immediately when MMTk calls `out_of_memory()` [1]. This is expectation is too strong and can lead to issues when trying to add proper OOM error reporting to bindings such as OpenJDK.

For more details, see this comment in the OpenJDK binding: https://github.com/mmtk/mmtk-openjdk/issues/78#issuecomment-1025287199

\[1]: https://github.com/mmtk/mmtk-core/blob/4851e7ac7e8a7bd70ce65935c4ac1ff430cab6f1/src/vm/collection.rs#L66-L73

**Comment by qinsoon** [comment]
According to the information [here](https://mmtk.zulipchat.com/#narrow/stream/262674-mmtk-openjdk/topic/Proper.20OoM.20reporting/near/269977013), we probably want to deal different OOM cases differently. E.g. failing to get memory from OS would be dealt differently from exceeding the heap size limit.
