### ISSUE TITLE
Immix may go OOM even if there are recyclable lines if DEFRAG is not enabled

### ISSUE THREAD

**Issue by qinsoon** [mmtk/mmtk-core#586]
Immix only does page accounting at block level. When it adds up to the used pages when it gets a new block, and subtracts the pages when a block is freed. This means even if a block has free/recyclable lines, the entire block is counted as used.

If Immix is used without defrag (e.g. for a VM that does not support copying GC), and if the workload creates fragmentation in the heap, it is possible after a few GCs, each block contains at least one object. In this case, no block will be freed in a GC, and MMTK will trigger emergency GC several times (and still cannot free any block) and eventually go OOM. The OOM will happen even if there are recyclable lines.

I have seen a case with @udesou on one of Julia GC benchmarks, which creates objects at a pattern of 32 garbage objects (varying size of several bytes to 200 bytes for each object) + 1 live objects. Immix will go through several GCs and end up being unable to 'free' any block and trigger emergency GCs, and then panics on OOM. The live objects are estimated to be less than 2G in total, but Immix without defrag is unable to finish the benchmark with 16G heap. 

This is not an issue if defrag is enabled, as in emergency GCs, Immix will do defragmentation GC. So I am not sure if we will fix this.

**Comment by k-sareen** [comment]
Shouldn't Immix try to recycle lines first? Or are you saying that Immix will never revisit a partially free block even if it has recyclable lines? To me, that sounds like a good optimization to perform even if it's not in the original algorithm.

**Comment by qinsoon** [comment]
Immix does recycle lines. In allocation, Immix will recycle lines if possible. 

The issue is that our implementation does memory accounting on the block level. So at the end of a GC, for a block there are two cases for it:
* the block is completely empty. Immix space tells the page resource that the block is cleared, and subtracts the block from used pages.
* the block is not empty (it may have recycles lines), Immix does not clear the pages. In this case, we overcount the used pages, as we can possibly recycle lines in some of the pages.

If we go back to allocation after the GC, Immix can recycle the lines. But if after the GC, MMTk finds that the used pages still exceeds the heap size, it will immediately trigger an emergency GC. For immix, an emergency GC will do defrag -- unless defrag is disabled. So if defrag is disabled, and in a GC Immix cannot clear any empty block, it will eventually report OOM (even if there are recyclable lines). **This is only an issue if defrag is disabled.**

I would suggest this is a 'wont-fix' issue.

**Comment by k-sareen** [comment]
Aaah right I see the issue. Hmm. That is a tough issue. I think the issue naturally stems from heap fragmentation, though I didn't realize that fragmentation would be this severe in Julia.

**Comment by wenyuzhao** [comment]
I think counting memory only at the block level is intended. When you're running out of clean blocks, but still have plenty of reusable lines, this indicates that the heap fragmentation becomes an issue and you really need to do a "defrag GC".

Also, keeping tracking all the reusable lines in all the blocks will have additional overhead. You need to atomic update the heap accounting counters more frequently.

JikesRVM Immix only counts clean blocks as well. Maybe @steveblackburn can explain the intention of the design.

**Comment by wenyuzhao** [comment]
On the other hand, having plenty of reusable lines does not mean that the next allocation will always be successful. For allocations with medium to large (at least larger than a line size), it can fail without fitting into any reusable lines.

**Comment by qinsoon** [comment]
> Aaah right I see the issue. Hmm. That is a tough issue. I think the issue naturally stems from heap fragmentation, though I didn't realize that fragmentation would be this severe in Julia.

It is just the workload which specifically tests fragmentation. And the GC (immix without defrag) could not handle the fragmentation.

**Comment by qinsoon** [comment]
> I think counting memory only at the block level is intended. When you're running out of clean blocks, but still have plenty of reusable lines, this indicates that the heap fragmentation becomes an issue and you really need to do a "defrag GC".
> 
> Also, keeping tracking all the reusable lines in all the blocks will have additional overhead. You need to atomic update the heap accounting counters more frequently.
> 
> JikesRVM Immix only counts clean blocks as well. Maybe @steveblackburn can explain the intention of the design.

Yeah, we can quickly discuss this in our meeting. My feeling is that we probably won't do anything for this. It mostly just affects immix with defrag disabled.

**Comment by qinsoon** [comment]
If defrag is disabled, reducing immix block size can mitigate this issue. By default, the block size is 32K. Without defrag, using 8K or even 4K block size may help. We do not plan to introduce this change to mmtk-core though.
