### ISSUE TITLE
Feature: Do not move root objects in Immix

### ISSUE THREAD

**Issue by qinsoon** [mmtk/mmtk-core#591]
This feature would be helpful if a binding allows moving non-root objects, but not root objects. E.g. they are doing conservative stack scanning. The idea is simple: for root edges, we need to tell Immix to mark the objects but not copy them.

**Comment by k-sareen** [comment]
This could just be implemented by object pinning, right? If you are using conservative roots, then we can just pin the roots.

**Comment by qinsoon** [comment]
> This could just be implemented by object pinning, right? If you are using conservative roots, then we can just pin the roots.

Right. But pinning requires using object metadata for a pinning bit. This does not need extra object metadata.

**Comment by k-sareen** [comment]
Closed with https://github.com/mmtk/mmtk-core/pull/897
