### ISSUE TITLE
Allow the plan to be set as a command-line flag

### ISSUE THREAD

**Issue by chrisseaton** [mmtk/mmtk-core#623]
We'd like to be able to set the plan via a flag on the command line.

https://github.com/mmtk/mmtk-ruby/issues/1

I can see the comment about why this is not possible at the moment. How deep does this design assumption go? Should we alleviate it sooner rather than later?

```
// The plan to use. This needs to be initialized before creating an MMTk instance (currently by setting env vars)
```

Slightly higher priority for me is at least having a more sensible default plan - either a different default hard-coded into MMTk itself, or being able to set a different default in our VM (which would then mean we can also implement the flag.)

We'd like people to be able to just run our VM as normal, without having to set an environment variable.

Or, as a workaround is it safe to set the environment variable ourselves, within the VM, before we first use MMTk? Is that sensible?

CC @qinsoon

**Comment by qinsoon** [comment]
> Or, as a workaround is it safe to set the environment variable ourselves, within the VM, before we first use MMTk? Is that sensible?

Yeah, that is possible. However, you would have to set the environment variables before creating a `MMTK` instance (not before first using MMTk). That may not be easy unless you create the MMTk instance lazily.

Ideally the issue will go away with https://github.com/mmtk/mmtk-core/issues/541. But that would be a much significant refactoring. I will think about if there is a workaround.

**Comment by qinsoon** [comment]
I did some refactoring in https://github.com/mmtk/mmtk-core/pull/625. Now plan (and all the other options) can be set from command line. Setting options through env vars still works though.
