### ISSUE TITLE
Confusing API: scan_thread_roots vs scan_thread_root

### ISSUE THREAD

**Issue by qinsoon** [mmtk/mmtk-core#640]
I think one of them is used for a given binding based on their constants in `Scanning`. From the document, it is unclear which one will be used. We need to tidy up the code around this, and make it clear in the document which one will be used.

**Comment by wks** [comment]
Related issue: https://github.com/mmtk/mmtk-core/issues/601  We may rename those two functions accordingly.

**Comment by qinsoon** [comment]
Duplicate of https://github.com/mmtk/mmtk-core/issues/601.
