### ISSUE TITLE
`MonotonePageResource.acquire` returns address within metadata pages

### ISSUE THREAD

**Issue by wenyuzhao** [mmtk/mmtk-core#65]
When `META_DATA_PAGES_PER_REGION` is not set to zero, `MonotonePageResource` with discontiguous space fail to skip metadata pages during page allocation.

This may leads to some objects being misplaced within metadata pages.

*Not sure if this is a bug, or an intentional design.*

# Reproduce the bug using SemiSpace GC

1. Change [CopySpace's metadata pages](https://github.com/mmtk/mmtk-core/blob/master/src/policy/copyspace.rs#L18) to a non-zero value.
2. Make sure SemiSpace's copyspaces uses discontiguous vm-requrests, [here](https://github.com/mmtk/mmtk-core/blob/master/src/plan/semispace/ss.rs#L73-L76)
3. Add the following assertion to [this line](https://github.com/mmtk/mmtk-core/blob/master/src/util/alloc/bumpallocator.rs#L123) of BumpPointer's alloc-slow method

```rust
if self.space.unwrap().common().name.starts_with("copyspace") {
    assert!(::util::alloc::embedded_meta_data::get_metadata_base(acquired_start) != acquired_start);
}
```
4. You will see an assertion failure, means that the `MonotonePageResource` returned a 4MB-aligned address, without skipping the metadata pages.

# Cause of the bug (a guess)

`MonotonePageResource` does successfully skip metadata pages during page allocation. See code [here](https://github.com/mmtk/mmtk-core/blob/master/src/util/heap/monotonepageresource.rs#L94).

But `MonotonePageResource` with discontiguous space lately overwrites this value without skipping meta-pages, [at here](https://github.com/mmtk/mmtk-core/blob/master/src/util/heap/monotonepageresource.rs#L112).

**Comment by qinsoon** [comment]
Is this already fixed with https://github.com/mmtk/mmtk-core/pull/136? @wenyuzhao
