### ISSUE TITLE
Don't print to stdout on NoGC GC request output

### ISSUE THREAD

**Issue by chrisseaton** [mmtk/mmtk-core#654]
This warning makes testing hard for me, because it's always printed, right on stdout. Can it be a proper logging line instead, disabled at a level when it doesn't appear by default? Or not included at all because it's obvious that `NoGC` won't do a GC.

https://github.com/mmtk/mmtk-core/blob/76131c493be38e421f5fb157f9900f850584554f/src/plan/nogc/global.rs#L83

CC @wks.

**Comment by qinsoon** [comment]
It should be a warn level log. I will fix that.
