### ISSUE TITLE
Investigate use and performance of `inline` directives

### ISSUE THREAD

**Issue by k-sareen** [mmtk/mmtk-core#733]
We're fairly liberal with our usage of `inline` directives (be it `inline(always)` or `inline(never)`). Ideally we let the compiler make inlining decisions except for the hot loop (like `trace_object`) which we may have to tune for maximum performance.

Inlining too much can lead to too many register spills and an increase in code size which can lead to very hard to debug performance issues (for example, we may see a random performance drop if code moves around).

**Comment by qinsoon** [comment]
As discussed, we probably will remove the current compiler directives, and use [profile-guided optimisation](https://rustc-dev-guide.rust-lang.org/profile-guided-optimization.html) to generate Rust binary (or use it to force inlining etc). We can just use one benchmark to profile, we may either have one profile per plan, or use the default 'production' plan (the fastest plan).

**Comment by k-sareen** [comment]
I'll close this issue after having investigated the affects of different profiling steps. I will update the best practices in both mmtk-core and mmtk-openjdk then.

**Comment by k-sareen** [comment]
[Internal link](http://squirrel.anu.edu.au/plotty/kunals/bench-test/p/3Fnxqd). We ran an experiment which tried different ways to generate the PGO profile. The different profiles were:

1. `master` (106fc714), no inlining, no PGO
2. PGO profile generated using `GenImmix` with a stress factor of 4 MB and 3 invocations
3. PGO profile generated using `GenImmix` with a stress factor of 4 MB and 1 invocation
4. PGO profile generated using `GenImmix` with a stress factor of 16 MB and 1 invocation
5. PGO profile generated using `GenImmix`, `Immix, and `SemiSpace` with a stress factor of 4 MB and 1 invocation for each profiling GC
6. PGO profile generated using `GenImmix`, `Immix, and `SemiSpace` with a stress factor of 16 MB and 1 invocation for each profiling GC

From the results we can see that for the stop-the-world time, `Immix` and `SemiSpace` perform worse than the baseline (build 1) for builds 2-4, while exceed the baseline for builds 5-6 by around 5-6%. For `GenImmix` all PGO builds perform better than the baseline, however, build 1 and build 6 are the only ones with 5%+ improvements to the stop-the-world time. Overall **build 6 is the clear winner** in terms of performance across GCs.

Hence, it is preferred that the profiling step include multiple GCs. I will run another short experiment that runs a GC that was not explicitly profiled (like `GenCopy` for example) in order to see if the profiles (specially build 6) are general enough to improve the performance of other collectors. Note that whenever LXR lands in mmtk-core, we will have to redo our profiling to include LXR as it is unlikely that RC operations would be correctly optimized by the above profile(s).

I'll make a PR for mmtk-core and mmtk-openjdk updating the best practices for making a PGO build.

**Comment by qinsoon** [comment]
My understanding of the results are:
* As long as the profile includes a plan, we can get good performance for the plan (e.g. if we profile A+B+C, we can run the build with A or B or C with good performance, but not necessarily the absolute best performance -- but it is close enough).
* If the profile does not include a plan, the build may perform worse than no PGO, and we should not use the build to measure the plan. 
* For quick turnaround, using no PGO is okay (~5% slowdown in STW time, almost neglectable slowdown in total time).

**Comment by k-sareen** [comment]
> As long as the profile includes a plan, we can get good performance for the plan (e.g. if we profile A+B+C, we can run the build with A or B or C with good performance, but not necessarily the absolute best performance -- but it is close enough).

Yes. But it may be that a combination of the profiling plans may provide a good enough profile. This is what the `GenCopy` experiment will check. But yes I agree with the other points.

**Comment by qinsoon** [comment]
> > As long as the profile includes a plan, we can get good performance for the plan (e.g. if we profile A+B+C, we can run the build with A or B or C with good performance, but not necessarily the absolute best performance -- but it is close enough).
> 
> Yes. But it may be that a combination of the profiling plans may provide a good enough profile for unprofiled plans. This is what the `GenCopy` experiment will check. But yes I agree with the other points.

Your profile (Build6) includes `ImmixSpace` and `CopySpace`. `GenCopy` uses `CopySpace` so it may benefit from the profile. You could also try with `MarkSweep` or `MarkCompact` (which does not use `ImmixSpace` and `CopySpace` at all).

**Comment by k-sareen** [comment]
Technically `GenImmix` already includes `CopySpace` so `GenImmix` + `Immix` may be good enough to get the same benefits. But at this point I don't think it's useful to fine-tune the profile generation step. If it's good enough (which it certainly is) then that's all that matters, imo.

> You could also try with MarkSweep or MarkCompact (which does not use ImmixSpace and CopySpace at all).

Yeah that's a fair point -- both of those GCs are so inefficient though so I don't know if actually care about their performance that much. I'll run them after `GenCopy` just in the background while doing other work. I think we would have satisfactorily answered the PGO question after the `GenCopy` experiment.

**Comment by k-sareen** [comment]
GenCopy: [Internal link](http://squirrel.anu.edu.au/plotty/kunals/bench-test/p/gbGVe8).

Interesting that the profiles are almost always better than baseline except for xalan.

**Comment by qinsoon** [comment]
We have removed all the inline directives, and totally rely on the compiler and profile-guided optimization.
