### ISSUE TITLE
Typo in `build_info.rs`?

### ISSUE THREAD

**Issue by wenyuzhao** [mmtk/mmtk-core#739]
https://github.com/mmtk/mmtk-core/blob/844aa0ea5c8c6c4eec6d1336495a14dbcd025718/src/build_info.rs#L14

`a96e8f9` is repeated twice.

**Comment by caizixian** [comment]
I think it's meant to be `a96e8f9-dirty`

**Comment by caizixian** [comment]
@qinsoon can clarify

**Comment by qinsoon** [comment]
Yeah, should be `-dirty`.
