### ISSUE TITLE
Make env_logger optional

### ISSUE THREAD

**Issue by wks** [mmtk/mmtk-core#744]
Currently, mmtk-core includes a `log` backend, that is, `env_logger`.  It also attempts to configure the `env_logger` in `memory_manager::mmtk_init`.  This approach, although convenient, may have a problem when the VM wants to include its own logging settings for various reasons.  For example,

1.  The VM binding also uses logs, and wants to log messages before `mmtk_init`.
2.  The VM has some parts written in Rust, too, and they also need logging. (Ruby's YJIT is written in Rust.)

We can have `env_logger` guarded behind a Cargo feature, or the other way around -- adding a Cargo feature to *not* include `env_logger` as part of our dependencies.

**Comment by qinsoon** [comment]
Sounds good. This could also be a runtime option.

Currently we create `env_logger` in `mmtk_init`, and we allow that to fail. That means the binding can initialize a Rust logger before calling `mmtk_init`
