### ISSUE TITLE
`Edge.{load,store}` should be marked `unsafe`

### ISSUE THREAD

**Issue by k-sareen** [mmtk/mmtk-core#787]
The load and store function for the [`Edge` type are marked as safe](https://github.com/mmtk/mmtk-core/blob/c634762cf1417fe2d8f17b1b7b41e14a951044c3/src/vm/edge_shape.rs#L42-L58). This doesn't make sense as it's loading from an arbitrary address so it must be marked `unsafe`.

**Comment by qinsoon** [comment]
If those methods are unsafe, can MMTk do anything to deal with the unsafety and to make safe use of it? No. MMTk still simply calls it with `unsafe { edge.load() }`. But MMTk cannot guarantee that this load is safe. In that case, it is meaningless to mark them as unsafe.

Also this is not loading from arbitrary addresses. It is loading from edges (known field slots). The implementation of the edge should ensure the load is correct. They can wrap `unsafe { addr.load() }` in their `edge.load` implementation, as they know the loading is correct.

**Comment by k-sareen** [comment]
> If those methods are unsafe, can MMTk do anything to deal with the unsafety and to make safe use of it? No. MMTk still simply calls it with unsafe { edge.load() }. But MMTk cannot guarantee that this load is safe. In that case, it is meaningless to mark them as unsafe.

It's the principle though. We mark the `Address.load` function as `unsafe` even though we can't make it safe. It's the same thing. Anything which effectively loads and stores to raw memory directly (as this is doing) should be marked `unsafe` I would say.

> Also this is not loading from arbitrary addresses. It is loading from edges (known field slots).

Yeah that's fair. But I still think it's lying a bit. It is very unsafe to directly load/store from memory.

**Comment by wks** [comment]
The point is, `Edge.{load,store}` doesn't have to load from (or store to) raw memory.  `SimpleEdge` does, but there may be other implementations that perform safe accesses only.  For example, Ruby developers may implement its "generic instance variable table" in Rust as a `HashMap<ObjectReference, Vec<RubyValue>>` where `gen_ivtbl[objref][field_index]` holds the field value.  In this way, an edge represented as a generic IVTBL entry is not unsafe to load or store.

The contract between the MMTk core and the VM binding is that

-   The VM binding implements `Edge`.
-   MMTk core simply calls `Edge.load` and it gets the object reference in it.

So the only obligation of MMTk core is calling `Edge.load`.  It is pointless for MMTk core to know whether `Edge.load` is safe or unsafe.  MMTk core always has to call it, and it has to trust the VM binding.

**Comment by qinsoon** [comment]
Another example is our side metadata. Internally, we use unsafe methods from `Address` to implement side metadata. But the atomic methods for side metadata (like atomic load and store) is not marked as 'unsafe', as the implementation of side metadata guarantees the load and store is from known valid addresses.

This is not 'lying', it is abstraction. A component could provide a safe abstraction using unsafe primitives. This is very common in Rust std lib as well. I feel we can close this issue now.

**Comment by k-sareen** [comment]
Yes fair enough. The above all makes sense. Thanks for the explanations.
