### ISSUE TITLE
Remove all `cast_ref_to_mut`

### ISSUE THREAD

**Issue by wenyuzhao** [mmtk/mmtk-core#850]
Transmuting a const ptr to a mutable ptr has become a hard compile error since rustc 1.72 https://github.com/rust-lang/rust/pull/111567

We need to consider refactoring and removing all the `cast_ref_to_mut` related code before upgrading to 1.72.

**Comment by Manishearth** [comment]
Note: if the shared mutation is a part of the design, and you can prove that the shared mutation never overlaps with any reads, the way to avoid that UB is to store `lxr` etc as `UnsafeCell<LXR<...>>` and use the UnsafeCell methods to get mutable references. Rust _does_ allow for the C model of shared mutation using cell types, however there is still UB possible with `UnsafeCell`.

I recommend trying to refactor it such that `unsafe` is not needed.

**Comment by playXE** [comment]
This PR fixes UB using NonNull<> and UnsafeCell where appropriate everywhere: https://github.com/mmtk/mmtk-core/pull/893
