### ISSUE TITLE
Document MSRV policy for mmtk-core

### ISSUE THREAD

**Issue by wks** [mmtk/mmtk-core#878]
# Problem

Currently the MSRV for mmtk-core (the `package.rust-version` attribute in Cargo.toml) is "1.61.0".  That version was [released one year ago](https://blog.rust-lang.org/2022/05/19/Rust-1.61.0.html).  Now several of our dependency libraries require a higher MSRV, and some of our code can also make use of features introduced in later versions of Rust.  We need a MSRV policy so that we can systematically bump the MSRV periodically.

We [added the `package.rust-version` attribute](https://github.com/mmtk/mmtk-core/commit/3026ad8c68b1504768a76c483ed1ec66a3176a36) about 15 months ago, and [bumped the MSRV](https://github.com/mmtk/mmtk-core/commit/0d5b54548fdfdf337f3d01a7da7bfce5f12edd10) once.  We have been reluctant to bump MSRV, so we need a documented our policy so that we can do so more eagerly in a principled way.

# Factors that affect our decisions

We need to ensure **our development and testing infrastructure** work with the MSRV of mmtk-core and supported bindings.  
We used to hold the MSRV to ensure mmtk-core could still be compiled and tested on the `*.moma` machines which our developers in the ANU use.  Now those machines have the latest Rust toolchain installed.

We need to ensure **our major consumers** can use MMTk with the version they use.  Consumers should include

-   Organisations that deployed MMTk in a production setting, and
-   Researchers that are doing on-going research (not published, yet) starting from a fork of MMTk, but cannot merge with the master branch.  They may need to cherry-pick changes from the master branch from time to time.

Currently this should not be a problem because the Rust toolchain has very good backward compatibility so that the latest Rust toolchain don't break existing code.  So there is no reason to stick to an old version.  (Correct me if I am wrong.)

*p.s. It [happened once](https://github.com/mmtk/mmtk-core/issues/691) that updating to a later version caused some problem, but that was because our code contained undefined behaviour.  We should test our code with the latest stable version to fix such issues as soon as poossible.*

# Suggested MSRV policy

I suggest we support "N-1" (the latest Rust stable version plus one previous stable version) or "N-3" (latest plus three previous), depending on how aggressive we want to be.

Given that the release cycle or Rust is 6 weeks, N-1 is about three months and N-3 is about six months from the oldest supported version the newest supported version.  

# When do we bump MSRV?

Given that MMTk core also has a release cycle of every 6 weeks, we should bump the MSRV **after** we make a release.  (It is *after* rather than before, because all commits made before the release were tested on the MSRV just before the release.)

After bumping the MSRV, we should also update the dependency versions.

We should also make a `// TODO` note when we found some code can be implemented more efficiently using newer features introduced since a given Rust release.  We can refactor those code after we bump MSRV.

**Comment by k-sareen** [comment]
Closed with #881
