### ISSUE TITLE
Performance regression between 20230113 and 20230208

### ISSUE THREAD

**Issue by qinsoon** [mmtk/mmtk-core#902]
For all the plans we tested (nogc, gencopy, semispace), there was a slowdown of ~10% between those two dates on `fop`.
https://www.mmtk.io/ci-perf-result/master/openjdk_semispace_history.html
https://www.mmtk.io/ci-perf-result/master/openjdk_gencopy_history.html
https://www.mmtk.io/ci-perf-result/master/openjdk_nogc_history.html

**Comment by qinsoon** [comment]
This might not be an MMTk regression. We also see a slowdown in mutator performance for OpenJDK stock GCs: https://www.mmtk.io/ci-perf-result/master/mutator_history.html

We move our CI machines to Ubuntu 22.04 during that period.

**Comment by k-sareen** [comment]
Also @qinsoon I think more importantly we removed inline attributes and started using PGO in that time period. I'm almost certain that it is the likely cause.

**Comment by k-sareen** [comment]
Also 2023-02-08 bumped the Rust version. Perhaps that's the cause. Since the inline attributes were actually removed on 2023-02-13 and not 2023-02-08.

**Comment by qinsoon** [comment]
There is also a similar slowdown for OpenJDK stock GCs in mutator time. It could be some system changes.

**Comment by caizixian** [comment]
> This might not be an MMTk regression. We also see a slowdown in mutator performance for OpenJDK stock GCs: https://www.mmtk.io/ci-perf-result/master/mutator_history.html
> 
> We move our CI machines to Ubuntu 22.04 during that period.

Yes. That was on Jan 16 2023.

**Comment by qinsoon** [comment]
I cannot reproduce the performance regression. What we observed as a regression should be a consequence of the running environment change. I don't plan to spend more time to investigate the actual issue right now.

## Current: 
* binding: 91e163a3e7961232189c5f2c8496c1b4a75a4f9b

MMTk NoGC
```console
yilin@rat:~/Code/openjdk_workspace/openjdk$ MMTK_PLAN=NoGC build/jdk-mmtk-master/jdk/bin/jav
a -Xms2000M -Xmx2000M  -XX:MetaspaceSize=100M -server -XX:-TieredCompilation -XX:+UseThirdPa
rtyHeap -Dprobes=MMTk -cp /home/yilin/Code/ci-perf-kit/running/../probes/probes.jar:/usr/sha
re/benchmarks/dacapo/dacapo-2006-10-MR2.jar Harness -n 2 fop
===== DaCapo fop starting warmup =====
===== DaCapo fop completed warmup in 1497 msec =====
===== DaCapo fop starting =====
===== DaCapo fop PASSED in 867 msec =====
```
G1 (large heap, no gc)
```console
yilin@rat:~/Code/openjdk_workspace/openjdk$ build/jdk-mmtk-master/jdk/bin/java -Xms2000M -Xm
x2000M  -XX:MetaspaceSize=100M -server -XX:-TieredCompilation -Dprobes=MMTk -cp /home/yilin/Code/ci-perf-kit/running/../probes/probes.jar:/usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar Harness -n 2 fop
===== DaCapo fop starting warmup =====
===== DaCapo fop completed warmup in 1483 msec =====
===== DaCapo fop starting =====
===== DaCapo fop PASSED in 883 msec =====
```
## Jan 13:
* mmtk-core: 541020b65bcd1aa4723fc9868d18de34b4463fa3
* binding: 19ec1e027e6305e7e3f11b342f1acab6c56d6baf
* Rust version: 1.66.1 (The results we got from CI was based on 1.59.0, but we don't have 1.59.0 right now on our dev machines. However, it is unlikely to be an issue from Rust version).

MMTk NoGC
```console
yilin@rat:~/Code/openjdk_workspace/openjdk$ MMTK_PLAN=NoGC build/jdk-mmtk-jan-13/jdk/bin/jav
a -Xms2000M -Xmx2000M  -XX:MetaspaceSize=100M -server -XX:-TieredCompilation -XX:+UseThirdPa
rtyHeap -Dprobes=MMTk -cp /home/yilin/Code/ci-perf-kit/running/../probes/probes.jar:/usr/sha
re/benchmarks/dacapo/dacapo-2006-10-MR2.jar Harness -n 2 fop
===== DaCapo fop starting warmup =====
===== DaCapo fop completed warmup in 1469 msec =====
===== DaCapo fop starting =====
===== DaCapo fop PASSED in 865 msec =====
```

G1 (large heap, no gc)
```console
yilin@rat:~/Code/openjdk_workspace/openjdk$ build/jdk-mmtk-jan-13/jdk/bin/java -Xms2000M -Xm
x2000M  -XX:MetaspaceSize=100M -server -XX:-TieredCompilation -Dprobes=MMTk -cp /home/yilin/
Code/ci-perf-kit/running/../probes/probes.jar:/usr/share/benchmarks/dacapo/dacapo-2006-10-MR
2.jar Harness -n 2 fop
===== DaCapo fop starting warmup =====
===== DaCapo fop completed warmup in 1467 msec =====
===== DaCapo fop starting =====
===== DaCapo fop PASSED in 878 msec =====
```
