### ISSUE TITLE
Binding perf compare CI is broken

### ISSUE THREAD

**Issue by caizixian** [mmtk/mmtk-core#906]
For example, https://github.com/mmtk/mmtk-core/actions/runs/5877259952

**Comment by qinsoon** [comment]
The perf compare CI is working. It needs to be manually triggered in actions: https://github.com/mmtk/mmtk-core/actions/workflows/perf-compare-ci.yml

This issue https://github.com/mmtk/mmtk-core/issues/282 talks about better presentation of the results.
