### ISSUE TITLE
Incorrect collection_pages calculation in mem balancer

### ISSUE THREAD

**Issue by qinsoon** [mmtk/mmtk-core#918]
The mem balancer paper uses a metric called 'bytes collected during GC'. I interpreted as 'bytes reclaimed'. But it turned out to be incorrect. It should actually be 'bytes traversed during GC'.

Basically our calculation for the following field is wrong. We should fix this.
https://github.com/mmtk/mmtk-core/blob/9175e68a92484ecc6b4fac9db0a58f149f3386fb/src/util/heap/gc_trigger.rs#L188

As we use pages for our calculation (such as live pages, and allocation pages), the question for us is that how we can get the number of pages traversed by the GC. Earlier we added a way to count traversed bytes (https://github.com/mmtk/mmtk-core/pull/768), but it counts bytes not pages. We probably can calculate traversed pages from live pages and promoted pages.

**Comment by wks** [comment]
Alternatively, we can count non-empty pages during the release stage.  This can avoid introducing cost during the transitive closure.

**Comment by qinsoon** [comment]
We have reserved pages, which is non-empty pages. But that does not always equal to pages we traversed in a GC. There are memory that is alive and reserved, but is not traversed in a GC. Like unreachable objects in immortal spaces, or mature objects in a nursery GC.

**Comment by k-sareen** [comment]
Can you point to the page in the paper which mentions it's traversed pages and not collected pages?

**Comment by qinsoon** [comment]
In Fig 4 of the paper, when it refers to 'bytes collected during collection', it means 'bytes traversed by the GC' rather than 'bytes freed by the GC' (we checked with the author).

**Comment by k-sareen** [comment]
Ah right. This is just a heuristic anyway, so maybe it's fine to just use live bytes instead of traversed bytes.
