### ISSUE TITLE
Discontiguous MarkCompactSpace support

### ISSUE THREAD

**Issue by wenyuzhao** [mmtk/mmtk-core#930]
Currently, the MarkComapctSpace relies on `self.common.start`, which is only set for contiguous spaces: https://github.com/mmtk/mmtk-core/blob/master/src/policy/markcompactspace.rs#L322

This brings an implicit assumption that the MarkCompactSpace can work correctly only when being configured as contiguous. Although it's constructor actually supports discontiguous layout https://github.com/mmtk/mmtk-core/blob/master/src/policy/markcompactspace.rs#L202-L206.

This is a blocker for the openjdk compressed oops support, as it will enable discontiguous MarkCompactSpace for MarkCompact plan.

**Comment by wks** [comment]
If I read the code of MonotonicPageResource correctly, it chains up all the "contiguous chunks" in a doubly linked list, with `CommonPageResource::head_discontiguous_region` pointing to the last "contiguous chunks" obtained from `Map32`.  We can follow this linked list and fill up each "contiguous chunks" when computing forwarding pointers.

**Comment by wenyuzhao** [comment]
> If I read the code of MonotonicPageResource correctly, it chains up all the "contiguous chunks" in a doubly linked list, with `CommonPageResource::head_discontiguous_region` pointing to the last "contiguous chunks" obtained from `Map32`. We can follow this linked list and fill up each "contiguous chunks" when computing forwarding pointers.

Yeah I'll try to use this to fix it. I did this on Java MMTk before.
