### ISSUE TITLE
Side forwarding bits are not cleared properly

### ISSUE THREAD

**Issue by wks** [mmtk/mmtk-core#972]
When the forwarding bits metadata is on the side, we use an optimization which only clears the forwarding bits for blocks that are "defrag sources".  This approach is problematic.

-   For StickyImmix, young objects can be moved, too, if Immix is configured to prefer evacuating young objects in minor GCs.
-   In theory, Immix can opportunistically move any objects at any time, even if the current GC is not a defrag GC.  Although we are currently not doing this (the Immix plan only moves objects if the current GC is defrag GC), we should prepare for this possibility.

It is better to ensure the on-the-side forwarding bits are cleared after each GC so that when GC starts, forwarding bits will always be zero.

It is easier (and more general) to clear the forwarding bits for all live blocks, like how we clear the on-the-side mark bits.  We can do this as long as the performance overhead is minimal.  For performance, we may choose to only clear forwarding bits for blocks or lines where objects may actually be moved.

*Note: The best solution is always **using in-header forwarding bits** instead of on-the-side forwarding bits.  When a new object is allocated, the entire object will be zeroed, which implicitly clears the in-header forwarding bits.  The forwarding bits can be placed anywhere in the object as long as a given bit is guaranteed to be zero when GC happens.  That's because when an object is forwarded, its from-space copy is "condemned" which means its contents will never be accessed again.  However, we allow on-the-side forwarding bits because some VMs do not have any extra bits to spare in the object headers.*

**Comment by playXE** [comment]
So I have a question regarding this. My binding uses in-header forwarding bits yet the bug occurs with StickyImmix only. Why would it happen in the first place if not this defrag check in `get_forwarded_object` and `is_live`?

**Comment by wks** [comment]
> So I have a question regarding this. My binding uses in-header forwarding bits yet the bug occurs with StickyImmix only. Why would it happen in the first place if not this defrag check in `get_forwarded_object` and `is_live`?

I think that is a bug.  I implemented `get_forwarded_object` for ImmixSpace when developing the Ruby binding which uses on-the-side forwarding bits.  Ruby currently only supports Immix, but not StickyImmix, and that is why I didn't test it thoroughly with StickyImmix.

It didn't break other VM bindings because `get_forwarded_object` is only used during weak reference processing.
-   Only Ruby is actively using `get_forwarded_object` in weak reference processing.
-   The OpenJDK binding relies on the ReferenceProcessor implementation in mmtk-core, which uses `trace_object` instead of `get_forwarded_object` to get the forwarded pointer.
-   The JikesRVM binding currently only supports MarkSweep and SemiSpace, which don't have this bug.
-   V8 also uses `get_forwarded_object` in weak reference processing, but its master branch currently only supports NoGC.
-   The Julia binding uses `trace_object`, too.

So it is, well, quite unfortunate that this bug is not triggered by any of our officially supported bindings.

But from the practice of other bindings, if you use in-header forwarding bits, you may use `trace_object` instead of `get_forwarded_object` as a temporary workaround.

**Comment by qinsoon** [comment]
https://github.com/mmtk/mmtk-core/pull/969 is a related PR.

Basically there are two separate but related issues here:
1. The defrag block check is incorrect. It affects both header forwarding bits and side forwarding bits.
2. Side forwarding bits are not cleared so `get_forwarded_object()` may give a wrong result based on the forwarding bits. This affects only side forwarding bits, as header forwarding bits are cleared when a new object is allocated in a reused block.

The defrag block check was introduced in attempt to fix 2.
