### ISSUE TITLE
MockVM

### ISSUE THREAD

**Issue by qinsoon** [mmtk/mmtk-core#99]
For testing, we include a `DummyVM` in the mmtk-core repo. We should rename it to `MockVM` to properly reflect its usage. And we should allow proper mocking for testing.

**Comment by qinsoon** [comment]
We have gradually added some tests to `DummyVM` to MMTk core: https://github.com/mmtk/mmtk-core/tree/master/vmbindings/dummyvm/src/tests

We would at some point refactor `DummyVM` into a proper `MockVM`. Specifically, we need to be able to define the MockVM's behavior per each test. 

For example, currently, when a GC is triggered for a `DummyVM`, we simply panic.
https://github.com/mmtk/mmtk-core/blob/0babba20290d3c4e4cdb2a83284aa7204c9a23cc/vmbindings/dummyvm/src/collection.rs#L20
In the test in which we expect a GC to be triggered, we check if the test panics
https://github.com/mmtk/mmtk-core/blob/0babba20290d3c4e4cdb2a83284aa7204c9a23cc/vmbindings/dummyvm/src/tests/allocate_with_re_enable_collection.rs#L8
and in the test in which we expect no GC to be triggered, we simply see if the test passes without panic
https://github.com/mmtk/mmtk-core/blob/0babba20290d3c4e4cdb2a83284aa7204c9a23cc/vmbindings/dummyvm/src/tests/allocate_with_disable_collection.rs#L8

The panic behavior of `block_for_gc()` makes it impossible for us to use the binding for any GC test, as it will panic whenever a GC is triggered. We would expect that `MockVM` would allow us to define `block_for_gc()` per each test case.

The simplest approach is to use function pointers. `MockVM` forwards each call to a separate function pointer, and the function pointer initially points to a default implementation. Each test can create their own function, and update the function pointer for certain API calls.

@wks @KipHamiltons

**Comment by wks** [comment]
I have another example.

I want my `is_mmtk_object` feature to work for different VMs.  The offsets from the allocated address and the object reference is different among VMs, So I want my test cases to control the behaviour of `ObjectModel::object_start_ref` of a VM.
